#!/bin/sh
#// launchWSJTX
#// Launch the SDR receiver and after that WSJT-X with a profile depending on the hour
#//
#// See accompanying README
#// file for a description on how to use this code.
#// based on the package WsprryPi (https://github.com/JamesP6000/WsprryPi)
#// License:
#//   This program is free software: you can redistribute it and/or modify
#//   it under the terms of the GNU General Public License as published by
#//   the Free Software Foundation, either version 2 of the License, or
#//   (at your option) any later version.
#//
#//   This program is distributed in the hope that it will be useful,
#//   but WITHOUT ANY WARRANTY; without even the implied warranty of
#//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#//   GNU General Public License for more details.
#//
#//   You should have received a copy of the GNU General Public License
#//   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#// lu7did: initial load
#*----------------------------------------------------------------------------
#* Initialization
#* DO NOT RUN EITHER AS A rc.local script nor as a systemd controlled service
#*----------------------------------------------------------------------------
cd /home/pi

H=$(date +"%H")
if [ $H -ge 12 ] && [ $H -lt 18 ]; then
   MODE="ft8"
else
   MODE="wspr"
fi

echo "Launching WSJT-X mode($MODE)" | logger -t WSJTX
./whisper/receiver.sh $MODE
wsjtx -r $MODE

